In [2]:
import torch
from tqdm.notebook import tqdm

from transformers import BertTokenizer
from torch.utils.data import TensorDataset

from transformers import BertForSequenceClassification

import pickle

In [6]:
# Load: insert variable to load pickle into
df1 = pickle.load(open('../data/pickle/aristotle_hate.pickle', 'rb'))

# Load: insert variable to load pickle into
df2 = pickle.load(open('../data/pickle/aristotle_abusive.pickle', 'rb'))

# Load: insert variable to load pickle into
df3 = pickle.load(open('../data/pickle/aristotle_neutral.pickle', 'rb'))

In [8]:
df4 = pickle.load(open('../data/pickle/copenhagen_2.pickle', 'rb'))

In [9]:
df1

,public_metrics,text,id,created_at,entities,geo
0,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",I hate er chase because if the Bitch that work...,850433664890544128,2017-04-07T19:42:40.000Z,NaN,NaN
1,"{'retweet_count': 5, 'reply_count': 0, 'like_c...",RT @nyctophil3: Pineapples do not belong on pi...,850100742035836929,2017-04-06T21:39:45.000Z,"{'mentions': [{'start': 3, 'end': 14, 'usernam...",NaN
2,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",Niggas keep talking about women wearing weave ...,847804507367100416,2017-03-31T13:35:20.000Z,NaN,NaN
3,"{'retweet_count': 0, 'reply_count': 1, 'like_c...",@vappywave idiot that's not gonna work. you go...,850090319165050880,2017-04-06T20:58:20.000Z,"{'mentions': [{'start': 0, 'end': 10, 'usernam...",NaN
4,"{'retweet_count': 5, 'reply_count': 0, 'like_c...",RT @ayevonnn: bruh i fucking hate people like ...,848686686930382848,2017-04-03T00:00:48.000Z,"{'urls': [{'start': 53, 'end': 76, 'url': 'htt...",NaN
...,...,...,...,...,...,...
1699,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",Baekhyun won 'Most Popular Artist of Korea'\n\...,850701219568001025,2017-04-08T13:25:50.000Z,"{'annotations': [{'start': 0, 'end': 7, 'proba...",NaN
1700,"{'retweet_count': 0, 'reply_count': 1, 'like_c...",#TripleTalaqArrest 2fgt dis social menace #Tri...,849316180670259205,2017-04-04T17:42:11.000Z,"{'hashtags': [{'start': 0, 'end': 18, 'tag': '...",NaN
1701,"{'retweet_count': 0, 'reply_count': 0, 'like_c...",White nationalists' latest tactic to recruit c...,849674709763358720,2017-04-05T17:26:51.000Z,"{'urls': [{'start': 85, 'end': 108, 'url': 'ht...",NaN
1702,"{'retweet_count': 1, 'reply_count': 0, 'like_c...",We are in a comfortable lead fight against gal...,849246676854484992,2017-04-04T13:06:00.000Z,"{'hashtags': [{'start': 53, 'end': 66, 'tag': ...",NaN
1703,"{'retweet_count': 0, 'reply_count': 1, 'like_c...",Took him less than a minute...!! Gutless grub!...,849635522389651456,2017-04-05T14:51:08.000Z,"{'urls': [{'start': 121, 'end': 144, 'url': 'h...",NaN

In [ ]:
# 1: pd.Series, 2: list or pd.index, each item labels individual bars
Y = 
X = 
fig = plt.figure(figsize = (8, 5))
g = sns.barplot(X, Y, palette='deep')
# Insert title for graph, y axis label, and x axis label
g.set(title = 'deep', ylabel = '', xlabel = '')
plt.tight_layout()
plt.show()
# Insert filename to save
plt.savefig('')